### ISSUE TITLE
Fatal error after creating a mezzio project with "composer create-project mezzio/mezzio-skeleton"

### ISSUE THREAD

**Issue by xserrat** [mezzio/mezzio#77] opened 2021-05-29 17:12 UTC
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 3.2.1

#### Summary

When installing the skeleton of mezzio using the following command:
```php
composer create-project mezzio/mezzio-skeleton .
```
I get an error when loading the home page:

![image](https://user-images.githubusercontent.com/5933658/120078724-2b1d0a80-c0b1-11eb-9789-f3ee3b22d467.png)

#### How to reproduce

* Run `composer create-project mezzio/mezzio-skeleton .`
* Run `php -S 0.0.0.0:9000 -t public/`

Also, the problem was solved running `composer update`.

#### Expected behavior

I expect the following home page:

![image](https://user-images.githubusercontent.com/5933658/120078763-599ae580-c0b1-11eb-8db7-0faabcb9c00f.png)

**Comment by Xerkus** [comment] 2021-05-29 17:19
Duplicate of #71

**Comment by Xerkus** [comment] 2021-05-29 17:19
This was already resolved in later version. Run `composer update`

**Closed as completed by Xerkus** 2021-05-29 17:19 UTC
Labels: Duplicate
