### ISSUE TITLE
InvalidConfigProviderException: Mezzio\Helper\ConfigProvider is registered more than once

### ISSUE THREAD

**Issue by rhengles** [mezzio/mezzio#203] opened 2024-12-02 15:44 UTC
### Bug Report

|    Q    |   A
|---- | ----
| Windows | 10
| PHP | 8.2.26 (cli) (built: Nov 19 2024 18:15:04) (NTS Visual C++ 2019 x64)

|    Q    |   A (require)
|---- | ----
| php  | ~8.1.0 \|\| ~8.2.0 \|\| ~8.3.0
| composer/package-versions-deprecated | ^1.10.99
| laminas/laminas-component-installer | ^2.6 \|\| ^3.0
| laminas/laminas-config-aggregator| ^1.6
| laminas/laminas-diactoros | ^3.0.0
| laminas/laminas-stdlib | ^3.6
| mezzio/mezzio | ^3.7
| mezzio/mezzio-helpers | ^5.7
| laminas/laminas-servicemanager | ^3.22
| mezzio/mezzio-fastroute | ^3.11.0

|    Q    |   A (require-dev)
|---- | ----
| laminas/laminas-coding-standard | ~2.5.0
| laminas/laminas-development-mode | ^3.12.0
| mezzio/mezzio-tooling | ^2.9
| phpunit/phpunit | ^10.5.5
| psalm/plugin-phpunit | ^0.18.4
| roave/security-advisories | dev-master
| vimeo/psalm | ^5.18
| filp/whoops | ^2.15.4

#### Summary

Just created a new project from scratch
```sh
composer create-project mezzio/mezzio-skeleton mezzio
```
When finishing the creation, the script runs: `php bin/clear-config-cache.php`
However this throws the following error:

```sh
Fatal error: Uncaught Laminas\ConfigAggregator\InvalidConfigProviderException: Mezzio\Helper\ConfigProvider is
registered more than once. Config providers should be unique. In case a specific order is required, please double
check before deleting the duplicate(s). in ***\vendor\laminas\laminas-config-aggregator\src
\InvalidConfigProviderException.php:15
Stack trace:
    #0 ***\vendor\laminas\laminas-config-aggregator\src\ConfigAggregator.php(117): Laminas\ConfigAggregator\InvalidConfigProviderException::fromDuplicateProvider('Mezzio\\Helper\\C...')
    #1 ***\vendor\laminas\laminas-config-aggregator\src\ConfigAggregator.php(85): Laminas\ConfigAggregator\ConfigAggregator->validateNoDuplicateProviders(Array)
    #2 ***\config\config.php(16): Laminas\ConfigAggregator\ConfigAggregator->__construct(Array, 'data/cache/conf...')
    #3 ***\bin\clear-config-cache.php(9): include('***\project\...')
    #4 {main}
  thrown in ***\vendor\laminas\laminas-config-aggregator\src\InvalidConfigProviderException.php on line 15
```

#### Current behavior

The create script throws the error above.

#### How to reproduce

Just create a new mezzio project in Windows

#### Expected behavior

Script creates a blank project without errors.

I did this afterwards to fix the problem:
```diff
 # file /config/config.php
-    \Mezzio\Helper\ConfigProvider::class,
+    // \Mezzio\Helper\ConfigProvider::class,
```

**Comment by samsonasik** [comment] 2024-12-02 15:50
/cc @alexmerlin that's probably related with PR:

- https://github.com/laminas/laminas-config-aggregator/pull/47

**Comment by gsteel** [comment] 2024-12-02 16:29
Possible duplicate of https://github.com/mezzio/mezzio-skeleton/issues/161

**Closed as not planned** 2024-12-02 19:08 UTC
Labels: Bug, Duplicate
