### ISSUE TITLE
 jsoumelidis/zend-sf-di-config[0.4.0, ..., 0.4.1] require php ^7.1 -> your php version 8.0.99

### ISSUE THREAD

**Issue by oleg-moseyko** [mezzio/mezzio#162] opened 2023-06-09 10:13 UTC
### Bug Report

 jsoumelidis/zend-sf-di-config supported only php ^7.1

#### Summary

$ composer create-project mezzio/mezzio-skeleton mezzio
Creating a "mezzio/mezzio-skeleton" project at "./mezzio"
Info from https://repo.packagist.org: #StandWithUkraine
Installing mezzio/mezzio-skeleton (3.14.0)
  - Installing mezzio/mezzio-skeleton (3.14.0): Extracting archive
Created project in /Users/olegmoseyko/Projects/mezzio
> MezzioInstaller\OptionalPackages::install
Setting up optional packages
Setup data and cache dir
Removing installer development dependencies

  What type of installation would you like?
  [1] Minimal (no default middleware, templates, or assets; configuration only)
  [2] Flat (flat source code structure; default selection)
  [3] Modular (modular source code structure; recommended)
  Make your selection (2): 2
  - Copying src/App/ConfigProvider.php

  Which container do you want to use for dependency injection?
  [1] Pimple (supported by laminas)
  [2] laminas-servicemanager (supported by laminas)
  [3] Symfony DI Container
  [4] PHP-DI
  [5] chubbyphp-container
  Make your selection or type a composer package name and version (laminas-servicemanager (supported by laminas)): 3
  - Adding package jsoumelidis/zend-sf-di-config (^0.4)
  - Copying config/container.php

  Which router do you want to use?
  [1] FastRoute (supported by laminas)
  [2] laminas-router (supported by laminas)
  Make your selection or type a composer package name and version (FastRoute (supported by laminas)): 2
  - Adding package mezzio/mezzio-laminasrouter (^3.0.1)
  - Whitelist package mezzio/mezzio-laminasrouter
  - Copying config/routes.php

  Which template engine do you want to use?
  [1] Plates (supported by laminas)
  [2] Twig (supported by laminas)
  [3] laminas-view installs laminas-servicemanager (supported by laminas)
  [n] None of the above
  Make your selection or type a composer package name and version (n): 3
  - Adding package mezzio/mezzio-laminasviewrenderer (^2.2)
  - Whitelist package mezzio/mezzio-laminasviewrenderer
  - Copying templates/error/404.phtml
  - Copying templates/error/error.phtml
  - Copying templates/layout/default.phtml
  - Copying templates/app/home-page.phtml

  Which error handler do you want to use during development?
  [1] Whoops (supported by laminas)
  [n] None of the above
  Make your selection or type a composer package name and version (Whoops (supported by laminas)): 1
  - Adding package filp/whoops (^2.7.1)
  - Copying config/autoload/development.local.php.dist
Remove installer
Removing composer.lock from .gitignore
Removing Mezzio installer classes, configuration, tests and docs
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
- Required package "jsoumelidis/zend-sf-di-config" is not present in the lock file.
- Required package "mezzio/mezzio-laminasrouter" is not present in the lock file.
- Required package "mezzio/mezzio-laminasviewrenderer" is not present in the lock file.
This usually happens when composer files are incorrectly merged or the composer.json file is manually edited.
Read more about correctly resolving merge conflicts https://getcomposer.org/doc/articles/resolving-merge-conflicts.md
and prefer using the "require" command over editing the composer.json file directly https://getcomposer.org/doc/03-cli.md#require-r

$ cd mezzio/
192:mezzio olegmoseyko$ composer install
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. It is recommended that you run `composer update` or `composer update <package name>`.
- Required package "jsoumelidis/zend-sf-di-config" is not present in the lock file.
- Required package "mezzio/mezzio-laminasrouter" is not present in the lock file.
- Required package "mezzio/mezzio-laminasviewrenderer" is not present in the lock file.
This usually happens when composer files are incorrectly merged or the composer.json file is manually edited.
Read more about correctly resolving merge conflicts https://getcomposer.org/doc/articles/resolving-merge-conflicts.md
and prefer using the "require" command over editing the composer.json file directly https://getcomposer.org/doc/03-cli.md#require-r
192:mezzio olegmoseyko$ composer update
Loading composer repositories with package information
Info from https://repo.packagist.org: #StandWithUkraine
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - jsoumelidis/zend-sf-di-config[0.4.0, ..., 0.4.1] require php ^7.1 -> your php version (8.0.99; overridden via config.platform, actual: 8.1.1) does not satisfy that requirement.
    - Root composer.json requires jsoumelidis/zend-sf-di-config ^0.4 -> satisfiable by jsoumelidis/zend-sf-di-config[0.4.0, 0.4.1].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

**Comment by froschdesign** [comment] 2023-06-09 10:28
Duplicate of https://github.com/mezzio/mezzio-skeleton/issues/130

**Closed as not planned by froschdesign** 2023-06-09 10:28 UTC
Labels: Duplicate
